# Generated by Django 4.2.27 on 2026-01-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_name',
        ),
    ]
