# Generated by Django 4.2.26 on 2025-11-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_projects_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='url',
        ),
    ]
