# Generated by Django 4.2.27 on 2026-01-31 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ydlidar', models.BooleanField()),
                ('numberOfInercialSensors', models.IntegerField()),
                ('settings', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('robot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_robot', to='loginApp.robot')),
            ],
        ),
    ]
