# Generated by Django 4.2.27 on 2026-01-31 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_configurationprofile_sensorreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='RobotTechnitian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_technitian', to='loginApp.technitian'),
        ),
    ]
