# Generated by Django 4.2.27 on 2026-02-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_alter_robot_robottechnitian'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='fav',
            field=models.BooleanField(default=False),
        ),
    ]
