# Generated by Django 4.2.27 on 2025-12-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('web_server', models.CharField(blank=True, choices=[('Apache', 'Apache'), ('Nginx', 'Nginx')], max_length=50)),
                ('role', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Engineer', 'Engineer'), ('Manager', 'Manager'), ('Guest', 'Guest')], max_length=50)),
            ],
        ),
    ]
