# Generated by Django 4.2.26 on 2025-11-14 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
