# Generated by Django 4.2.26 on 2025-11-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_remove_projects_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
